apiVersion: v1
kind: Service
metadata:
  name: control-vm
  namespace: {{ .Values.username }}-travel-control
  labels:
    app: control-vm
spec:
  ports:
    - port: 8080
      name: http
  selector:
    kubevirt.io/domain: control-vm
