---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.username }}-travel-control
  annotations:
    openshift.io/description: "Travel Control Namespace for {{ .Values.username }}"
    openshift.io/display-name: "Travel Control Namespace for {{ .Values.username }}"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Values.username }}-travel-control
  namespace: {{ .Values.username }}-travel-control
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: {{ .Values.username }}
