---
apiVersion: argoproj.io/v1beta1
kind: ArgoCD
metadata:
  name: argocd
  namespace: {{ .Values.username }}-travel-control
spec:
  sso:
    dex:
      openShiftOAuth: true
    provider: dex
  rbac:
    policy: |
      g, system:cluster-admins, role:admin
      g, cluster-admins, role:admin
      g, {{ .Values.username }}, role:admin
    scopes: '[name,groups]'
  server:
    route:
      enabled: true
      tls:
        insecureEdgeTerminationPolicy: Redirect
        termination: reencrypt
