---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.username }}-travel-control-new
  annotations:
    openshift.io/description: "Travel Control NEW Namespace"
    openshift.io/display-name: "Travel Control NEW Namespace"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Values.username }}-travel-control-new
  namespace: {{ .Values.username }}-travel-control-new
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: {{ .Values.username }}
